from dataframe_corrupter.corrupter import DataFrameCorrupter
from dataframe_corrupter.strategy.drop_rows_strategy import DropRowsStrategy
from dataframe_corrupter.strategy.add_noise_strategy import AddNoiseStrategy
from dataframe_corrupter.strategy.add_negative_values_strategy import AddNegativeValuesStrategy
from dataframe_corrupter.strategy.add_nulls_strategy import AddNullsStrategy
from dataframe_corrupter.strategy.add_typos_strategy import AddTyposStrategy
from dataframe_corrupter.strategy.add_duplicate_rows_strategy import AddDuplicateRowsStrategy